# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afada65ec91fcccbe47f367d1cc57e4871e5dbb2a2236f33b8245e47cb9b5dfd72139ddf1cfa9a50a3a9e8210066c00fc8017ce4bb5236a8f1740c04fd9311cc

test:
  secret_key_base: 34671cab63993720d148ecfce8f79e75721d672a5a7e49fc0f1a7952e15a45c6a40041ca5b93a057e9a8905a7ef053fc893553d1a23e88e4a0e6f8915226b778

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
